-- upgrade --
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(20) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8;
CREATE TABLE IF NOT EXISTS `city` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `province` VARCHAR(100) NOT NULL UNIQUE COMMENT '省/直辖市',
    `country` VARCHAR(100) NOT NULL  COMMENT '国家',
    `country_code` VARCHAR(100) NOT NULL  COMMENT '国家代码',
    `country_population` BIGINT NOT NULL  COMMENT '国家人口'
) CHARACTER SET utf8;
CREATE TABLE IF NOT EXISTS `data` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `date` DATE NOT NULL  COMMENT '数据日期',
    `confirmed` BIGINT NOT NULL  COMMENT '确诊数量' DEFAULT 0,
    `deaths` BIGINT NOT NULL  COMMENT '死亡数量' DEFAULT 0,
    `recovered` BIGINT NOT NULL  COMMENT '痊愈数量' DEFAULT 0,
    `city_id` INT NOT NULL,
    CONSTRAINT `fk_data_city_85658398` FOREIGN KEY (`city_id`) REFERENCES `city` (`id`) ON DELETE CASCADE
) CHARACTER SET utf8;
